name: Performance benchmarks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write
  deployments: write
  pull-requests: write

jobs:
  benchmark:
    name: Performance
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake

    - name: Build project
      run: make

    - name: Run google benchmarks
      run: |
        ./build_release/test/perf_raft_leader_election --benchmark_format=json > perf_le.json
        ./build_release/test/perf_raft_peers --benchmark_format=json > perf_peers.json
        ./build_release/test/perf_raft_serialization --benchmark_format=json > perf_srl.json

        # Склеиваем сырой вывод в один массив
        jq -s '[.[].benchmarks] | flatten' perf_le.json perf_peers.json perf_srl.json > perf_raft_merged.json

        # Подготавливаем плоский список с указанием suite для экшена
        jq '[ .[] |
          if .name | startswith("leader_election<") and endswith(" (Real Time)") then
            { suite: "Leader Election (Real Time)", name: (.name | capture("<(?<v>\\d+)>") | .v + " nodes"), value: .value, unit: .unit }
          elif .name | startswith("leader_election<") and endswith(" (CPU Time)") then
            { suite: "Leader Election (CPU Time)", name: (.name | capture("<(?<v>\\d+)>") | .v + " nodes"), value: .value, unit: .unit }
          elif .name | startswith("leader_election_default<") and endswith(" (Real Time)") then
            { suite: "Leader Election Default (Real Time)", name: (.name | capture("<(?<v>\\d+)>") | .v + " nodes"), value: .value, unit: .unit }
          elif .name | startswith("leader_election_default<") and endswith(" (CPU Time)") then
            { suite: "Leader Election Default (CPU Time)", name: (.name | capture("<(?<v>\\d+)>") | .v + " nodes"), value: .value, unit: .unit }
          elif .name | startswith("check_contact_quorum/threads:") and endswith(" (Real Time)") then
            { suite: "Check Contact Quorum (Real Time)", name: (.name | capture("threads:(?<t>\\d+)") | .t + " threads"), value: .value, unit: .unit }
          elif .name | startswith("request_to_list/threads:") and endswith(" (Real Time)") then
            { suite: "Request to List (Real Time)", name: (.name | capture("threads:(?<t>\\d+)") | .t + " threads"), value: .value, unit: .unit }
          elif .name | startswith("request_lock_list/threads:") and endswith(" (Real Time)") then
            { suite: "Request Lock List (Real Time)", name: (.name | capture("threads:(?<t>\\d+)") | .t + " threads"), value: .value, unit: .unit }
          elif .name == "serialize_message (Real Time)" then
            { suite: "Serialize Message (Real Time)", name: "Base", value: .value, unit: .unit }
          else
            empty
          end
        ]' perf_raft_merged.json > perf_raft_common.json

    - name: Disable commit-msg hooks for bot
      run: rm -rf .git/hooks

    - name: Store and plot results
      uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: 'customSmallerIsBetter'
        external-data-json-path: perf_raft_common.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: ${{ github.event_name == 'push' }} # Update history charts only on push to master
        comment-on-alert: true                        # Post a performance change report in the PR comments
        fail-on-alert: false                          # Do not fail verification if performance drops
